kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: redis-master
  labels:
    app: redis
    role: master
    tier: backend
    type: amazonEBS
  annotations: 
    volume.beta.kubernetes.io/storage-class: standard
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
